# Generated by Django 2.1 on 2018-08-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='text',
            new_name='name',
        ),
    ]
