# Generated by Django 2.1 on 2018-08-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planners', '0002_auto_20180809_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='ENTER RECIPE DESCRIPTION'),
        ),
    ]
